AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TransactionsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: 'Transactions'
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'userAddress'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      GlobalSecondaryIndexes:
        - IndexName: 'userAddress-index'
          KeySchema:
            - AttributeName: 'userAddress'
              KeyType: 'HASH'
          Projection:
            ProjectionType: 'ALL'
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5